### ISSUE TITLE
Logo design proposal

### ISSUE THREAD

**Issue by Tobaloidee** [naturaln0va/RAScrollablePickerView#2]
Hi @naturaln0va Good day! I am a graphic designer and i would like to contribute to your nice project by designing a logo for it to be more visible. I will be doing it as a gift for free, I just need your permission first before i start. Thanks and best regard! - Tobaloidee

**Comment by naturaln0va** [comment]
That’s would be nice. You have the go ahead @Tobaloidee.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Tobaloidee** [comment]
Okay Sir..will start designing now and show you here after..thanks!

**Comment by Tobaloidee** [comment]
Here's my logo design for your project @naturaln0va  let me know what you have in mind.. :) I hope you like it.

concept: very direct representation of what the RAScrollablePickerView is all about. 3 scrollable color bars options. It is simple, clean and memorable which is also visible in any backgrounds. 

![pres-02](https://user-images.githubusercontent.com/36028424/42006803-a02b7b46-7aae-11e8-8023-b866fc0d3c15.png)

**Comment by naturaln0va** [comment]
@Tobaloidee thanks for this, it looks great! Would you mind adding it to the README and submitting it as a pull request and I'll merge it in! 👍

**Comment by Tobaloidee** [comment]
Surely! Will make a pr now after i prep the files

**Comment by Tobaloidee** [comment]
Here's the PR #3 with the logo and readme update 

Thanks! :)
